import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import { artFiles } from './tools/art-files.mjs';

/** Every file under public/, as paths relative to the site root. */
function publicFiles(dir = 'public'): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? publicFiles(p) : [relative('public', p).split('\\').join('/')];
  });
}

/**
 * Writes sw.js: a service worker that keeps the whole game (page, script,
 * fonts, icons) on the device so it plays offline. The cache name carries a
 * hash of the build, so a new deploy installs a fresh copy and the game can
 * offer "a new version is ready".
 */
function serviceWorker(): Plugin {
  return {
    name: 'kasva-sw',
    apply: 'build',
    enforce: 'post',
    generateBundle(_, bundle) {
      const files = ['./', ...Object.keys(bundle).filter((f) => !f.endsWith('.map')), ...publicFiles()].filter((f) => f !== 'sw.js');
      const hash = createHash('sha256');
      for (const f of Object.values(bundle)) hash.update(f.type === 'chunk' ? f.code : f.source);
      for (const f of publicFiles()) hash.update(readFileSync(join('public', f)));
      const version = hash.digest('hex').slice(0, 12);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(version, files) });
    },
  };
}

const swSource = (version: string, files: string[]) => `// Kasva! offline copy. Generated by vite.config.ts; do not edit.
const CACHE = 'kasva-${version}';
const FILES = ${JSON.stringify(files)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('kasva-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// The page asks for this when the player taps "Update".
self.addEventListener('message', (e) => { if (e.data === 'skip-waiting') self.skipWaiting(); });

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // Only the game's own page: other pages in sub-folders (the classroom sim) load normally.
    const home = new URL('./', location.href).pathname;
    const path = new URL(req.url).pathname;
    if (path !== home && path !== home + 'index.html') return;
    e.respondWith(caches.match('./', { cacheName: CACHE }).then((hit) => hit || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;

export default defineConfig(({ command }) => ({
  // Relative paths: the game works from any folder of any static host.
  base: './',
  define: {
    __PWA__: JSON.stringify(command === 'build'),
    // painted layers present in public/art (served, and cached for offline play)
    __ART__: JSON.stringify(Object.fromEntries(artFiles().map(([name, f]) => [name, `art/${f}`]))),
  },
  plugins: [serviceWorker()],
}));
