/**
 * Metsäni words, Finnish and English. Short sentences for ages 10–12, with
 * real Finnish forestry terms where a child could meet them.
 * Claims follow docs/forest-model.md: simplified, never presented as exact.
 */
import type { AnimalId, CauseKey, ChoiceId, DecisionKind, HealthReason, LifeReason, PlaceId, SoilId, SpeciesId, Spacing } from '../../core/forest';
import type { Lang } from '../text';

type Season = 'spring' | 'summer' | 'autumn' | 'winter';

const fi = {
  title: 'Metsäni',
  homeButton: 'Metsäni',
  tagline: 'Kasvata oma metsä vuosi vuodelta.',
  stepPlace: '1 · Missä metsäsi kasvaa?',
  stepSoil: '2 · Millainen maaperä?',
  stepTrees: '3 · Mitä istutat?',
  spacingTitle: 'Kuinka tiheään?',
  plant: 'Istuta!',
  back: 'Takaisin',
  continueForest: (y: number) => `Jatka metsää (vuosi ${y})`,
  newForest: 'Uusi metsä',
  pickOne: 'Valitse ainakin yksi puulaji.',
  earlier: 'Aiemmat metsäsi',
  earlierNote: 'Vertaa: missä metsä kasvoi parhaiten?',
  noEarlier: 'Ei vielä aiempia metsiä.',
  replaceWarn: 'Uusi metsä korvaa nykyisen. Nykyinen tallentuu vertailulistaan.',
  places: {
    south: { name: 'Etelä-Suomi', words: 'pitkä kesä · leuto talvi · vähän lunta' },
    east: { name: 'Itä-Suomi', words: 'keskipitkä kesä · luminen talvi · Kasva!-pelin koti' },
    lapland: { name: 'Lappi', words: 'lyhyt kesä · yötön yö · paljon lunta' },
    future: { name: 'Lämpimämpi tulevaisuus', words: 'pitkä kesä · kuivempi · vähemmän lunta' },
  } as Record<PlaceId, { name: string; words: string }>,
  soils: {
    sandy: { name: 'Hiekka', words: 'Vesi valuu läpi nopeasti. Mänty pärjää.' },
    clay: { name: 'Savi', words: 'Pitää vettä ja ravinteita, keväällä märkä.' },
    peat: { name: 'Turve (suo)', words: 'Märkä ja kylmä. Valtava hiilivarasto.' },
    loam: { name: 'Multava moreeni', words: 'Monipuolinen. Kuusi ja koivu viihtyvät.' },
    rocky: { name: 'Kallio', words: 'Ohut maa kallion päällä. Mänty pärjää parhaiten.' },
  } as Record<SoilId, { name: string; words: string }>,
  meterWater: 'vesi',
  meterFood: 'ravinteet',
  species: {
    pine: { name: 'Mänty', words: 'kestää kuivuutta, tarvitsee valoa' },
    spruce: { name: 'Kuusi', words: 'sietää varjoa, tarvitsee vettä ja ravinteita' },
    birch: { name: 'Koivu', words: 'nopea alussa, pudottaa lehtensä' },
    aspen: { name: 'Haapa', words: 'tulee itsestään, liito-oravan pesäpuu' },
  } as Record<SpeciesId, { name: string; words: string }>,
  spacing: { sparse: 'Harva', normal: 'Tavallinen', dense: 'Tiheä' } as Record<Spacing, string>,
  perHa: (n: number) => `${n} puuta / ha`,
  seasons: { spring: 'Kevät', summer: 'Kesä', autumn: 'Syksy', winter: 'Talvi' } as Record<Season, string>,
  year: (y: number) => `Vuosi ${y}`,
  play: 'Jatka',
  pause: 'Tauko',
  speedNormal: 'Normaali nopeus',
  speedFast: 'Nopeasti',
  jump10: '+10 vuotta',
  drought: 'Kuiva kesä',
  results: {
    wood: 'Puu', carbon: 'Hiili', life: 'Elämä', health: 'Terveys', products: 'Tuotteet',
  },
  woodValue: (m3: number) => `${m3} m³/ha`,
  carbonValue: (t: number) => `${t} t CO₂/ha`,
  productsNone: 'ei vielä',
  explain: {
    wood: (m3: string) => `Metsässäsi on puuta noin ${m3} kuutiometriä hehtaarilla. Paksut, suorat rungot ovat tukkeja, ohuet kuitupuuta.`,
    carbon: (removed: string, trees: string, soil: string) =>
      `Metsäsi on ottanut ilmasta yhteensä ${removed} t hiilidioksidia hehtaarilla. Puissa on hiiltä ${trees} t CO₂:ta vastaava määrä ja maaperässä ${soil} t.`,
    carbonNeg: 'Nuoressa metsässä maaperä vapauttaa vielä enemmän hiilidioksidia kuin pienet taimet ottavat. Se kääntyy, kun puut kasvavat.',
    life: {
      young: 'Metsä on vielä nuori. Elämä lisääntyy, kun puut vanhenevat ja lahopuuta kertyy.',
      oneSpecies: 'Yksi puulaji tarjoaa kodin harvoille lajeille. Sekametsässä on enemmän elämää.',
      mixed: 'Monta puulajia ja lehtipuita: sekametsä tarjoaa ruokaa ja suojaa monille lajeille.',
      deadwood: 'Lahopuu on koti monille sienille, kovakuoriaisille ja tikoille.',
      oldTrees: 'Isot, vanhat puut ovat tärkeitä koloissa pesiville linnuille ja liito-oravalle.',
    } as Record<LifeReason, string>,
    health: {
      fine: 'Puut voivat hyvin: vettä riittää ja tilaa on.',
      drought: 'Kesä oli kuiva. Puilta loppui vesi, ja ne kasvoivat vähemmän.',
      crowded: 'Metsä on liian tiheä. Puut kilpailevat valosta ja vedestä, ja heikoimmat kuolevat.',
      dying: 'Moni puu kuoli tänä vuonna. Kuolleista tulee lahopuuta.',
    } as Record<HealthReason, string>,
    products: 'Kun harvennat tai hakkaat metsää, puusta tulee lautoja, paperia ja energiaa. Vielä et ole hakannut puita.',
  },
  scoreOf: (s: number) => `${s} / 5`,
  tapTree: 'Napauta puuta nähdäksesi sen tiedot.',
  card: {
    planted: (y: number, age: number) => `Istutettu vuonna ${y} · ikä ${age} v`,
    height: 'Pituus', diameter: 'Rungon paksuus', wood: 'Runkopuuta', carbon: 'Hiiltä', co2: 'Ilmasta otettu CO₂',
    rings: 'Vuosilustot: leveä lusto = hyvä kasvuvuosi',
    light: { good: 'Saa paljon valoa', some: 'Osittain varjossa', poor: 'Varjossa, kasvaa hitaasti' },
    seedling: 'Taimi on vielä alle 1,3 metriä, joten paksuutta ei mitata.',
    kept: 'säästöpuu',
    close: 'Sulje',
  },
  // ---------- F2: questions, report, animals, what if ----------
  tikkaAsks: 'Tikka kysyy',
  questions: {
    regen: () => 'Metsä on hakattu. Mitä tänne kasvaa seuraavaksi? Suomessa metsälaki vaatii, että hakkuun jälkeen kasvatetaan uusi metsä.',
    young: () => 'Taimikko on tiheä. Raivataanko osa taimista?',
    crowded: () => 'Metsäsi on käymässä ahtaaksi. Puut kasvavat hoikiksi ja kilpailevat valosta.',
    mature: () => 'Moni puu on nyt iso ja vanha. Mitä seuraavaksi?',
    storm: (n: number) => `Myrsky kaatoi ${n} puuta. Kirjanpainajat lisääntyvät tuoreessa kuusipuussa.`,
    beetle: (n: number) => `Kirjanpainajat tappoivat ${n} kuusta.`,
    whatif: () => 'Mitä jos tekisit nyt jotain? Valitse kaksi vaihtoehtoa, niin näet ne rinnakkain.',
  } as Record<DecisionKind | 'whatif', (n: number) => string>,
  choices: {
    plant: ['Istuta taimet', 'Nopea alku, mutta istuttaminen on työtä.'],
    seed: ['Anna luonnon kylvää', 'Ilmaista ja luonnollista, mutta hitaampaa. Koivu tulee usein ensin.'],
    tend: ['Hoida taimikko', 'Ei puuta myyntiin, mutta jäljelle jäävät kasvavat paremmin (taimikonhoito).'],
    thin: ['Harvenna', 'Jäljelle jäävät saavat valoa ja vettä. Kaadetuista tulee kuitupuuta. Myrskyriski kasvaa hetkeksi (harvennus).'],
    thinLight: ['Harvenna kevyesti', 'Vähemmän puuta pois, pienempi muutos.'],
    nothing: ['Älä tee mitään', 'Hiili ja elämä kasvavat, mutta heikoimmat puut kuolevat itsestään.'],
    clearcut: ['Päätehakkuu ja uusi metsä', 'Paljon tukkeja ja tuotteita kerralla, sitten nuori metsä vuosikymmeniksi.'],
    clearcutKeep: ['Päätehakkuu, jätä säästöpuita', 'Muutama iso puu jää pysyvästi eläimille ja lahopuuksi (säästöpuut).'],
    cc: ['Kaada isoimmat, anna pienten kasvaa', 'Tasainen puuvirta ja metsä pysyy peitteisenä. Varjossa osa kasvaa hitaammin (jatkuva kasvatus).'],
    leaveOld: ['Anna kasvaa vanhaksi metsäksi', 'Hiili ja elämä lisääntyvät. Ei puuta myyntiin.'],
    removeFallen: ['Korjaa kaatuneet puut', 'Puu menee tehtaalle ja kuoriaisriski pienenee.'],
    removeHalf: ['Korjaa osa, jätä osa', 'Vähän molempia: puuta tehtaalle ja lahopuuta eläimille.'],
    leaveFallen: ['Jätä lahopuuksi', 'Koti monille lajeille, mutta kuoriaisriski kasvaa.'],
    removeBeetle: ['Kaada kuoriaispuut pois', 'Hidastaa leviämistä, mutta lahopuu vähenee.'],
    leaveBeetle: ['Jätä pystyyn', 'Tikat saavat ruokaa, mutta kuoriaisia voi tulla lisää.'],
  } as Record<ChoiceId, [string, string]>,
  plantTitle: 'Mitä istutat?',
  plantGo: 'Istuta',
  compareToggle: 'Mitä jos? Kokeile kahta',
  compareHint: 'Valitse kaksi vaihtoehtoa: ensimmäinen metsään A, toinen metsään B.',
  comparePickedA: (c: string) => `A: ${c}. Valitse vielä vaihtoehto metsään B.`,
  whatIfButton: 'Mitä jos?',
  forestA: 'Metsä A',
  forestB: 'Metsä B',
  sameWeather: 'Sama sää molemmissa metsissä: ainoa ero on valintasi.',
  keepA: 'Jatka metsällä A',
  keepB: 'Jatka metsällä B',
  cancel: 'Peruuta',
  report: {
    storm: (n: number) => `Syysmyrsky kaatoi ${n} puuta. Kuusi kaatuu helpoimmin, koska sen juuret ovat matalalla.`,
    beetle: (n: number) => `Kirjanpainajat tappoivat ${n} kuusta. Ne lisääntyvät kuivina kesinä ja tuoreessa kuusipuussa.`,
    thinned: () => 'Harvensit metsää. Jäljelle jääneet puut saavat nyt enemmän valoa ja vettä.',
    clearcut: () => 'Päätehakkuu: puut lähtivät tehtaalle, ja maahan jäi oksia ja kantoja lahoamaan.',
    cc: () => 'Kaadoit isoimmat puut. Pienet saavat nyt valoa, ja uusia taimia nousee.',
    salvaged: () => 'Korjasit vahingoittuneet puut. Puu meni tehtaalle, ja kuoriaisriski pieneni.',
    tended: () => 'Hoidit taimikon. Taimia on vähemmän, mutta ne kasvavat nyt nopeammin.',
    planted: () => 'Uudet taimet ovat maassa. Ensimmäiset vuodet ne kasvavat hitaasti.',
    seedlings: () => 'Luonto kylvää: koivun kevyet siemenet lentävät kauas, joten koivu ehtii usein ensin.',
    animal: () => 'Metsääsi tuli uusi laji!',
    drought: () => 'Kuiva kesä: maassa oli vähän vettä, joten puut kasvoivat vähemmän.',
    moose: (n: number) => `Hirvet söivät ${n} taimen latvoja. Mänty ja koivu maistuvat hirvelle, kuusi harvoin.`,
    grewFast: () => 'Hyvä kasvukesä! Lämpöä ja vettä riitti, joten puut kasvoivat tavallista enemmän.',
    grewSlow: () => 'Puut kasvoivat tavallista vähemmän. Viileä kesä tai ahdas metsä hidastaa kasvua.',
    crowded: () => 'Metsä on ahdas: puut kilpailevat valosta, ja heikoimmat kuolevat.',
    calm: () => 'Rauhallinen vuosi. Puut kasvoivat ja keräsivät hiiltä ilmasta.',
  } as Record<CauseKey, (n: number) => string>,
  animals: {
    moose: ['Hirvi', 'Hirvi syö nuorten mäntyjen, koivujen ja haapojen latvoja.'],
    blackWoodpecker: ['Palokärki', 'Tikan oma laji! Se tarvitsee isoja puita pesäksi ja lahopuuta, jossa on muurahaisia.'],
    spottedWoodpecker: ['Käpytikka', 'Käpytikka syö talvella kuusen ja männyn siemeniä kävyistä.'],
    capercaillie: ['Metso', 'Metso viihtyy vanhemmassa männikössä, jossa kasvaa mustikkaa.'],
    siberianJay: ['Kuukkeli', 'Kuukkeli asuu vanhoissa havumetsissä idässä ja pohjoisessa.'],
    treecreeper: ['Puukiipijä', 'Puukiipijä etsii hyönteisiä isojen puiden rosoisesta kaarnasta.'],
    flyingSquirrel: ['Liito-orava', 'Liito-orava pesii ison haavan kolossa ja liitää kuusten välillä.'],
  } as Record<AnimalId, [string, string]>,
  newSpecies: 'Uusi laji!',
  seenTitle: 'Metsässäsi nähdyt eläimet',
  seenNone: 'Ei vielä eläimiä. Ne tulevat, kun metsä tarjoaa niille ruokaa ja kodin.',
  reportClose: 'OK',
  productsMade: (sawn: string, paper: string, energy: string) => `Metsästäsi on tehty tuotteita: lautoja ja hirsiä ${sawn} t, paperia ja pahvia ${paper} t ja energiaa ${energy} t hiilidioksidiksi laskettuna. Laudat pitävät hiilen vuosikymmeniä, paperi vain pari vuotta, ja energiapuun hiili palaa ilmaan heti.`,
  canvasLabel: 'Metsäsi sivulta nähtynä: puut, maaperän leikkaus, vesi ja juuret.',
  yearDone: (y: number, vol: number) => `Vuosi ${y} päättyi. Puuta ${vol} kuutiometriä hehtaarilla.`,
  summary: (y: number, vol: number, co2: number) => `${y} v · ${vol} m³/ha · ${co2} t CO₂/ha`,
  speciesList: (names: string[]) => names.join(' + '),
};

type ForestText = typeof fi;

const en: ForestText = {
  title: 'Metsäni',
  homeButton: 'My forest',
  tagline: 'Grow your own forest, year after year.',
  stepPlace: '1 · Where does your forest grow?',
  stepSoil: '2 · What kind of soil?',
  stepTrees: '3 · What will you plant?',
  spacingTitle: 'How close together?',
  plant: 'Plant!',
  back: 'Back',
  continueForest: (y: number) => `Continue forest (year ${y})`,
  newForest: 'New forest',
  pickOne: 'Pick at least one tree species.',
  earlier: 'Your earlier forests',
  earlierNote: 'Compare: where did the forest grow best?',
  noEarlier: 'No earlier forests yet.',
  replaceWarn: 'A new forest replaces the current one. The current one is kept in the comparison list.',
  places: {
    south: { name: 'Southern Finland', words: 'long summer · mild winter · little snow' },
    east: { name: 'Eastern Finland', words: 'medium summer · snowy winter · Kasva!’s home' },
    lapland: { name: 'Lapland', words: 'short summer · midnight sun · deep snow' },
    future: { name: 'Warmer future', words: 'long summer · drier · less snow' },
  },
  soils: {
    sandy: { name: 'Sand', words: 'Water drains away fast. Pine copes.' },
    clay: { name: 'Clay', words: 'Holds water and food, soggy in spring.' },
    peat: { name: 'Peat (bog)', words: 'Wet and cold. A huge carbon store.' },
    loam: { name: 'Loamy till', words: 'The all-rounder. Spruce and birch thrive.' },
    rocky: { name: 'Rocky', words: 'Thin soil on rock. Pine copes best.' },
  },
  meterWater: 'water',
  meterFood: 'food',
  species: {
    pine: { name: 'Pine', words: 'copes with drought, needs light' },
    spruce: { name: 'Spruce', words: 'copes with shade, needs water and food' },
    birch: { name: 'Birch', words: 'fast starter, drops its leaves' },
    aspen: { name: 'Aspen', words: 'comes on its own, a nest tree for flying squirrels' },
  },
  spacing: { sparse: 'Sparse', normal: 'Normal', dense: 'Dense' },
  perHa: (n: number) => `${n} trees / ha`,
  seasons: { spring: 'Spring', summer: 'Summer', autumn: 'Autumn', winter: 'Winter' },
  year: (y: number) => `Year ${y}`,
  play: 'Play',
  pause: 'Pause',
  speedNormal: 'Normal speed',
  speedFast: 'Fast',
  jump10: '+10 years',
  drought: 'Dry summer',
  results: { wood: 'Wood', carbon: 'Carbon', life: 'Life', health: 'Health', products: 'Products' },
  woodValue: (m3: number) => `${m3} m³/ha`,
  carbonValue: (t: number) => `${t} t CO₂/ha`,
  productsNone: 'none yet',
  explain: {
    wood: (m3: string) => `Your forest holds about ${m3} cubic metres of wood per hectare. Thick, straight trunks are sawlogs (tukki); thin ones are pulpwood (kuitupuu).`,
    carbon: (removed: string, trees: string, soil: string) =>
      `Your forest has taken ${removed} t of carbon dioxide per hectare out of the air. The trees hold carbon worth ${trees} t of CO₂, and the soil ${soil} t.`,
    carbonNeg: 'In a young forest the soil still releases more carbon dioxide than the small seedlings take in. That turns around as the trees grow.',
    life: {
      young: 'The forest is still young. Life increases as the trees get older and deadwood gathers.',
      oneSpecies: 'One tree species gives a home to few others. A mixed forest holds more life.',
      mixed: 'Several tree species and broadleaves: a mixed forest gives food and shelter to many species.',
      deadwood: 'Deadwood is home to many fungi, beetles and woodpeckers.',
      oldTrees: 'Big old trees matter to birds that nest in holes, and to the flying squirrel.',
    },
    health: {
      fine: 'The trees are doing well: enough water and enough room.',
      drought: 'The summer was dry. The trees ran short of water and grew less.',
      crowded: 'The forest is too dense. The trees compete for light and water, and the weakest die.',
      dying: 'Many trees died this year. They become deadwood.',
    },
    products: 'When you thin or harvest, the wood becomes boards, paper and energy. You have not cut any trees yet.',
  },
  scoreOf: (s: number) => `${s} / 5`,
  tapTree: 'Tap a tree to see its details.',
  card: {
    planted: (y: number, age: number) => `Planted in year ${y} · age ${age}`,
    height: 'Height', diameter: 'Trunk width', wood: 'Stem wood', carbon: 'Carbon', co2: 'CO₂ taken from the air',
    rings: 'Tree rings: a wide ring = a good growing year',
    light: { good: 'Gets plenty of light', some: 'Partly shaded', poor: 'In the shade, growing slowly' },
    seedling: 'The seedling is still under 1.3 metres, so its trunk width is not measured.',
    kept: 'kept forever',
    close: 'Close',
  },
  tikkaAsks: 'Tikka asks',
  questions: {
    regen: () => 'The forest has been harvested. What grows here next? In Finland the Forest Act requires a new forest to be grown after a final harvest.',
    young: () => 'The young stand is dense. Clear out some of the saplings?',
    crowded: () => 'Your forest is getting crowded. The trees are growing thin and competing for light.',
    mature: () => 'Many trees are big and old now. What next?',
    storm: (n: number) => `A storm blew down ${n} trees. Spruce bark beetles breed in fresh spruce wood.`,
    beetle: (n: number) => `Bark beetles killed ${n} spruces.`,
    whatif: () => 'What if you did something now? Pick two choices and watch them side by side.',
  },
  choices: {
    plant: ['Plant seedlings', 'A fast start, but planting takes work.'],
    seed: ['Let nature seed', 'Free and natural, but slower. Birch often comes first.'],
    tend: ['Tend the saplings', 'No wood to sell, but the trees left grow better (taimikonhoito).'],
    thin: ['Thin', 'The trees left get light and water. The cut ones become pulpwood. Storm risk rises for a while (harvennus).'],
    thinLight: ['Thin lightly', 'Less wood out, a smaller change.'],
    nothing: ['Do nothing', 'Carbon and life build up, but the weakest trees die on their own.'],
    clearcut: ['Final harvest and a new forest', 'Lots of logs and products at once, then a young forest for decades.'],
    clearcutKeep: ['Final harvest, keep some trees', 'A few big trees stay forever, for animals and as deadwood (säästöpuut).'],
    cc: ['Cut the biggest, let small ones grow', 'A steady flow of wood and the forest stays covered. Some trees grow slower in the shade (continuous cover).'],
    leaveOld: ['Let it grow into old forest', 'Carbon and life increase. No wood to sell.'],
    removeFallen: ['Take out the fallen trees', 'The wood goes to the mill and the beetle risk drops.'],
    removeHalf: ['Take some, leave some', 'A bit of both: wood for the mill and deadwood for animals.'],
    leaveFallen: ['Leave them as deadwood', 'A home for many species, but the beetle risk rises.'],
    removeBeetle: ['Cut the beetle trees out', 'Slows the spread, but there is less deadwood.'],
    leaveBeetle: ['Leave them standing', 'Woodpeckers get food, but more beetles may come.'],
  },
  plantTitle: 'What will you plant?',
  plantGo: 'Plant',
  compareToggle: 'What if? Try two',
  compareHint: 'Pick two choices: the first goes to forest A, the second to forest B.',
  comparePickedA: (c: string) => `A: ${c}. Now pick a choice for forest B.`,
  whatIfButton: 'What if?',
  forestA: 'Forest A',
  forestB: 'Forest B',
  sameWeather: 'Both forests get the same weather: the only difference is your choice.',
  keepA: 'Keep forest A',
  keepB: 'Keep forest B',
  cancel: 'Cancel',
  report: {
    storm: (n: number) => `An autumn storm blew down ${n} trees. Spruce falls most easily because its roots are shallow.`,
    beetle: (n: number) => `Bark beetles killed ${n} spruces. They multiply in dry summers and in fresh spruce wood.`,
    thinned: () => 'You thinned the forest. The trees left now get more light and water.',
    clearcut: () => 'Final harvest: the trees went to the mills, and branches and stumps were left to rot.',
    cc: () => 'You cut the biggest trees. The small ones now get light, and new seedlings come up.',
    salvaged: () => 'You took out the damaged trees. The wood went to the mill and the beetle risk dropped.',
    tended: () => 'You tended the saplings. There are fewer, but they now grow faster.',
    planted: () => 'The new seedlings are in the ground. They grow slowly for the first years.',
    seedlings: () => 'Nature is seeding: light birch seeds fly far, so birch often comes first.',
    animal: () => 'A new species came to your forest!',
    drought: () => 'A dry summer: there was little water in the soil, so the trees grew less.',
    moose: (n: number) => `Moose ate the tops of ${n} saplings. They like pine and birch, rarely spruce.`,
    grewFast: () => 'A good growing summer! Enough warmth and water, so the trees grew more than usual.',
    grewSlow: () => 'The trees grew less than usual. A cool summer or a crowded forest slows growth.',
    crowded: () => 'The forest is crowded: the trees compete for light, and the weakest die.',
    calm: () => 'A calm year. The trees grew and took carbon from the air.',
  },
  animals: {
    moose: ['Moose', 'Moose eat the tops of young pines, birches and aspens.'],
    blackWoodpecker: ['Black woodpecker', 'Tikka’s own kind! It needs big trees to nest in and deadwood full of ants.'],
    spottedWoodpecker: ['Great spotted woodpecker', 'In winter it eats spruce and pine seeds from the cones.'],
    capercaillie: ['Capercaillie', 'It likes older pine forest with blueberries on the ground.'],
    siberianJay: ['Siberian jay', 'It lives in old conifer forests in the east and north.'],
    treecreeper: ['Treecreeper', 'It searches the rough bark of big trees for insects.'],
    flyingSquirrel: ['Flying squirrel', 'It nests in holes in big aspens and glides between spruces.'],
  },
  newSpecies: 'New species!',
  seenTitle: 'Animals seen in your forest',
  seenNone: 'No animals yet. They come when the forest gives them food and a home.',
  reportClose: 'OK',
  productsMade: (sawn: string, paper: string, energy: string) => `Your forest has become products: boards and beams ${sawn} t, paper and cardboard ${paper} t and energy ${energy} t, counted as carbon dioxide. Boards keep their carbon for decades, paper for a couple of years, and energy wood's carbon goes back to the air at once.`,
  canvasLabel: 'Your forest from the side: trees, a cut through the soil, water and roots.',
  yearDone: (y: number, vol: number) => `Year ${y} is over. ${vol} cubic metres of wood per hectare.`,
  summary: (y: number, vol: number, co2: number) => `${y} yrs · ${vol} m³/ha · ${co2} t CO₂/ha`,
  speciesList: (names: string[]) => names.join(' + '),
};

export const FOREST_TEXT: Record<Lang, ForestText> = { fi, en };
export type { Season };
