/** Game text. Finnish needs a native-speaker check before classroom use. */
export type Lang = 'fi' | 'en';

export const TEXT = {
  fi: {
    play: 'Kasva!',
    random: 'Uusi sää',
    theme: (date: string) => `Päivän sää · ${date}`,
    radio: (on: boolean) => `♪ Metsäradio · <b>${on ? 'päällä' : 'pois'}</b>`,
    howto: ['Pidä pohjassa: ilmaraot auki', 'Helle: lyhyitä henkäyksiä', 'Yöllä lepää'],
    keys: [['Välilyönti', 'hengitä'], ['P', 'tauko'], ['M', 'ääni']],
    day: 'Päivä',
    juhannus: 'Juhannus',
    weather: { sun: 'Aurinko', cloudy: 'Pilvistä', rain: 'Sade', heat: 'Helle' },
    water: 'VESI',
    stored: 'g CO₂ puussa',
    paused: 'Tauko',
    resume: 'Jatka',
    hints: {
      start: 'Pidä sormi ruudulla – lehtien ilmaraot avautuvat!',
      firstCatch: 'Nappasit hiilidioksidia! Valo tekee siitä sokeria, ja happea pääsee ulos.',
      dusk: 'Yö tulee. Ilman valoa hiilidioksidista ei ole hyötyä – päästä irti.',
      heat: 'Helle! Avoimista ilmaraoista haihtuu tuplasti vettä.',
      lowWater: 'Vesi vähissä – päästä irti, juuret täyttävät.',
      wilt: 'Puu nuupahti! Lehtiä putosi, ja nappausalue pieneni.',
      juhannus: 'Juhannusyö! Yö pysyy valoisana – voit jatkaa.',
      gold: 'Auringonpilkku! Auringossa kylpevä molekyyli on ×5.',
      rain: 'Sade täyttää vettä – nyt voi hengittää pitkään.',
      night: 'Puu hengittää hiilidioksidia ulos koko ajan, myös yöllä.',
    },
    result: {
      stored: 'g hiilidioksidia muuttui puuksi',
      caught: 'napattu',
      breathed: 'hengitetty ulos',
      combo: 'paras henkäys',
      wilts: 'nuupahdusta',
      again: 'Uudestaan',
      next: 'Uusi sää',
      copy: 'Kopioi tulos',
      copied: 'Kopioitu!',
      home: 'Metsään',
      best: 'Uusi ennätys!',
      tikka: {
        wilts: (n: number) => `Puusi nuupahti ${n} kertaa. Kun vesi on vähissä, päästä irti – juuret täyttävät.`,
        heat: (s: number) => `Pidit ilmaraot auki helteellä ${Math.round(s)} s. Helteellä vesi haihtuu tuplasti.`,
        night: (s: number) => `Pidit ilmaraot auki pimeässä ${Math.round(s)} s. Yöllä se vain kuluttaa vettä.`,
        resp: (p: number) => `${p} % napatusta hiilestä hengitettiin ulos yöllä. Puut hengittävät koko ajan.`,
      },
    },
    // ---------- progression (Phase 2) ----------
    nextSeason: 'Seuraava kesä',
    homeFree: 'Tarinakesät on pelattu! Kasvata omaa koivuasi, tai kokeile päivän säätä – siinä kaikilla on sama koivu.',
    daily: 'Päivän sää',
    cards: 'Kortit',
    story: (n: number, total: number) => `Tarina ${n}/${total}`,
    storyIntro: [
      'Hei, minä olen Tikka! Pidä sormi ruudulla, niin koivusi avaa ilmaraot ja nappaa hiilidioksidia.',
      'Pilvisenä päivänä valoa on vähemmän, joten jokainen nappaus tuottaa vähemmän sokeria.',
      'Ensimmäinen helle! Avoimista ilmaraoista haihtuu silloin tuplasti vettä.',
      'Sade täyttää vesivarastoa. Silloin voi hengittää pitkään.',
      'Kaksi hellettä samana kesänä. Lyhyet henkäykset säästävät vettä.',
      'Pilviä ja sadetta alussa, helle lopussa. Säästä vettä viimeiselle päivälle.',
      'Kaksi hellepäivää peräkkäin lopussa. Kerää hiiltä silloin, kun on viileämpää.',
      'Sade, helle ja taas sade. Lue sää ja hengitä sen mukaan.',
      'Helteitä tulee ja menee. Muista, että puu hengittää ulos myös yöllä.',
      'Viimeinen tarinakesä! Nyt osaat kaiken, mitä koivu tarvitsee.',
    ],
    ranks: {
      siemen: { name: 'Siemen', desc: 'Kaikki alkaa pienestä koivun siemenestä.' },
      itu: { name: 'Itu', desc: 'Siemen on itänyt, ja ensimmäiset lehdet nappaavat valoa.' },
      taimi: { name: 'Taimi', desc: 'Taimi kasvaa nopeasti, kun valoa ja vettä riittää.' },
      vesa: { name: 'Vesa', desc: 'Nuori puu, joka kasvaa jo pituutta joka kesä.' },
      riukupuu: { name: 'Riukupuu', desc: 'Pitkä ja hoikka nuori puu, kuin riuku.' },
      tukkipuu: { name: 'Tukkipuu', desc: 'Runko on niin paksu, että siitä voisi sahata lautaa.' },
      aarnipuu: { name: 'Aarnipuu', desc: 'Vanha ja mahtava puu, joka on varastoinut valtavasti hiiltä.' },
    },
    rankChip: (name: string, kg: number) => `${name} · ${kg.toLocaleString('fi-FI', { maximumFractionDigits: 1 })} kg`,
    streak: (n: number) => `${n} pv putki`,
    snowCover: 'Lumipeite suojaa yhden väliin jääneen päivän tällä viikolla.',
    xp: (kg: number, next: number | null) => next ? `${kg.toLocaleString('fi-FI', { maximumFractionDigits: 1 })} / ${next} kg CO₂` : `${kg.toLocaleString('fi-FI', { maximumFractionDigits: 1 })} kg CO₂`,
    levelUp: 'Uusi taso!',
    levelUpTikka: 'Puusi on kasvanut! Katso metsää – jotain uutta on ilmestynyt.',
    continue: 'Jatka',
    growTitle: 'Mihin sokeri käytetään?',
    growNote: 'Valitse yksi. Päivän säässä kaikilla on sama koivu, jotta kisa on reilu.',
    growDaily: 'Päivän säässä kaikilla on sama koivu, jotta kisa on reilu.',
    growth: {
      roots: { name: 'Juuret', effect: 'Isompi vesivarasto, joka täyttyy nopeammin.' },
      leaves: { name: 'Lehdet', effect: 'Enemmän hiilidioksidia joka nappauksella, mutta vettä haihtuu enemmän.' },
      wood: { name: 'Runko', effect: 'Pidempi runko nostaa latvan valoon.' },
    },
    chosen: (name: string, lvl: number) => `Valittu: ${name} ${lvl}/5`,
    newBadges: 'Uusi merkki!',
    cardsTitle: 'Merkit ja tietokortit',
    locked: 'Ansaitse merkki, niin kortti aukeaa.',
    close: 'Sulje',
    achievements: {
      'first-ring': { name: 'Ensimmäinen rengas', how: 'Pelaa yksi kesä.', fact: 'Joka kesä puu kasvattaa yhden vuosirenkaan. Renkaista voi laskea puun iän.' },
      'nightless-night': { name: 'Yötön yö', how: 'Nappaa hiilidioksidia juhannusyönä.', fact: 'Juhannuksena yö on niin valoisa, että lehdet saavat valoa lähes ympäri vuorokauden. Lapissa aurinko ei laske lainkaan.' },
      'wise-closer': { name: 'Viisas sulkija', how: 'Pidä ilmaraot kiinni koko helteen ajan, mutta kerää silti hiiltä muina päivinä.', fact: 'Kuumalla ja kuivalla säällä puut sulkevat ilmarakonsa säästääkseen vettä. Silloin ne myös kasvavat hitaammin.' },
      'breath-10': { name: 'Pitkä henkäys', how: 'Nappaa 10 molekyyliä yhdellä henkäyksellä.', fact: 'Koivun lehden alapinnalla on satoja tuhansia pieniä ilmarakoja.' },
      'no-wilt': { name: 'Ei nuupahdusta', how: 'Pelaa kesä nuupahtamatta ja kerää vähintään 1 500 g.', fact: 'Puu ottaa vettä juurillaan ja haihduttaa sitä lehdistään. Iso koivu voi haihduttaa kesäpäivänä kymmeniä litroja vettä.' },
      'week-streak': { name: 'Viikon putki', how: 'Pelaa seitsemänä päivänä peräkkäin.', fact: 'Hyvällä kasvupaikalla nuori koivu voi kasvaa jopa metrin vuodessa.' },
      'root-care': { name: 'Juurihoito', how: 'Valitse juuret kolme kertaa peräkkäin.', fact: 'Juurten kärjissä on hiusmaisia juurikarvoja, ja sienirihmat (mykorritsa) tuovat juurille vettä ja ravinteita.' },
      'ten-rings': { name: 'Kymmenen rengasta', how: 'Pelaa kymmenen kesää.', fact: 'Puun kuivapainosta noin puolet on hiiltä, ja lähes kaikki se tuli ilmasta hiilidioksidina.' },
      challenger: { name: 'Haastaja', how: 'Lähetä haaste kaverille (tulossa pian).', fact: 'Metsää on noin kolme neljäsosaa Suomen maapinta-alasta.' },
      overtake: { name: 'Ohitus', how: 'Voita kaverin haaste (tulossa pian).', fact: 'Palokärjen vanhoissa koloissa pesivät myöhemmin liito-oravat, pöllöt ja telkät.' },
    },
    log: 'Testiloki',
    logEmpty: 'Ei vielä pelattuja kesiä.',
    logClear: 'Tyhjennä',
    runs: (n: number) => `${n} kesää pelattu tällä laitteella`,
  },
  en: {
    play: 'Grow!',
    random: 'New weather',
    theme: (date: string) => `Today's weather · ${date}`,
    radio: (on: boolean) => `♪ Forest radio · <b>${on ? 'on' : 'off'}</b>`,
    howto: ['Hold: stomata open', 'Heatwave: short breaths', 'Night: rest'],
    keys: [['Space', 'breathe'], ['P', 'pause'], ['M', 'sound']],
    day: 'Day',
    juhannus: 'Midsummer',
    weather: { sun: 'Sun', cloudy: 'Cloudy', rain: 'Rain', heat: 'Heatwave' },
    water: 'WATER',
    stored: 'g CO₂ in the tree',
    paused: 'Paused',
    resume: 'Resume',
    hints: {
      start: 'Hold your finger on the screen – the stomata in the leaves open!',
      firstCatch: 'You caught carbon dioxide! Light turns it into sugar, and oxygen comes out.',
      dusk: 'Night is coming. Without light, CO₂ is no use – let go.',
      heat: 'Heatwave! Open stomata lose water twice as fast.',
      lowWater: 'Water is low – let go and the roots refill it.',
      wilt: 'Your tree wilted! It lost leaves and the catch zone shrank.',
      juhannus: 'Midsummer night! It stays light – keep going.',
      gold: 'Sunfleck! A molecule in a patch of sunlight is worth ×5.',
      rain: 'Rain refills your water – long breaths are fine now.',
      night: 'Your tree breathes CO₂ out all the time, at night too.',
    },
    result: {
      stored: 'g of carbon dioxide became wood',
      caught: 'caught',
      breathed: 'breathed out',
      combo: 'best breath',
      wilts: 'wilts',
      again: 'Again',
      next: 'New weather',
      copy: 'Copy result',
      copied: 'Copied!',
      home: 'To the forest',
      best: 'New best!',
      tikka: {
        wilts: (n: number) => `Your tree wilted ${n} times. When water is low, let go – the roots refill it.`,
        heat: (s: number) => `You kept your stomata open for ${Math.round(s)} s in the heatwave. Heat makes water vanish twice as fast.`,
        night: (s: number) => `You kept your stomata open in the dark for ${Math.round(s)} s. At night that only wastes water.`,
        resp: (p: number) => `${p}% of the carbon you caught was breathed out at night. Trees breathe all the time.`,
      },
    },
    // ---------- progression (Phase 2) ----------
    nextSeason: 'Next season',
    homeFree: "You've played the story summers! Grow your own birch, or try Today's weather, where everyone has the same birch.",
    daily: "Today's weather",
    cards: 'Cards',
    story: (n: number, total: number) => `Story ${n}/${total}`,
    storyIntro: [
      "Hi, I'm Tikka! Hold your finger on the screen and your birch opens its stomata to catch carbon dioxide.",
      'On a cloudy day there is less light, so each catch makes less sugar.',
      'Your first heatwave! Open stomata lose water twice as fast.',
      'Rain fills up your water. Long breaths are fine then.',
      'Two heatwaves in one summer. Short breaths save water.',
      'Clouds and rain first, a heatwave at the end. Save water for the last day.',
      'Two hot days in a row at the end. Catch carbon while it is cooler.',
      'Rain, heat, then rain again. Read the weather and breathe with it.',
      'Heatwaves come and go. Remember: your tree breathes out at night too.',
      'The last story summer! Now you know everything a birch needs.',
    ],
    ranks: {
      siemen: { name: 'Seed', desc: 'Everything starts from one small birch seed.' },
      itu: { name: 'Sprout', desc: 'The seed has sprouted, and its first leaves catch light.' },
      taimi: { name: 'Seedling', desc: 'A seedling grows fast when it has light and water.' },
      vesa: { name: 'Sapling', desc: 'A young tree that grows taller every summer.' },
      riukupuu: { name: 'Pole tree', desc: 'A tall, thin young tree, like a pole.' },
      tukkipuu: { name: 'Log tree', desc: 'The trunk is thick enough to saw into boards.' },
      aarnipuu: { name: 'Ancient tree', desc: 'An old, mighty tree that has stored a huge amount of carbon.' },
    },
    rankChip: (name: string, kg: number) => `${name} · ${kg.toLocaleString('en-GB', { maximumFractionDigits: 1 })} kg`,
    streak: (n: number) => `${n}-day streak`,
    snowCover: 'Snow cover protects one missed day this week.',
    xp: (kg: number, next: number | null) => next ? `${kg.toLocaleString('en-GB', { maximumFractionDigits: 1 })} / ${next} kg CO₂` : `${kg.toLocaleString('en-GB', { maximumFractionDigits: 1 })} kg CO₂`,
    levelUp: 'Level up!',
    levelUpTikka: 'Your tree has grown! Look at the forest – something new has appeared.',
    continue: 'Continue',
    growTitle: 'Where should the sugar go?',
    growNote: "Pick one. In Today's weather everyone has the same birch, so it's fair.",
    growDaily: "In Today's weather everyone has the same birch, so it's fair.",
    growth: {
      roots: { name: 'Roots', effect: 'A bigger water reserve that refills faster.' },
      leaves: { name: 'Leaves', effect: 'More CO₂ with every catch, but more water lost.' },
      wood: { name: 'Trunk', effect: 'A taller trunk lifts the crown into more light.' },
    },
    chosen: (name: string, lvl: number) => `Chosen: ${name} ${lvl}/5`,
    newBadges: 'New badge!',
    cardsTitle: 'Badges and fact cards',
    locked: 'Earn the badge to open this card.',
    close: 'Close',
    achievements: {
      'first-ring': { name: 'First ring', how: 'Play one season.', fact: 'Every summer a tree grows one ring. Count the rings to know its age.' },
      'nightless-night': { name: 'Nightless night', how: 'Catch carbon dioxide on Midsummer night.', fact: 'Around Midsummer the night is so light that leaves get light almost all day and night. In Lapland the sun does not set at all.' },
      'wise-closer': { name: 'Wise closer', how: 'Keep your stomata closed through a whole heatwave, but still catch carbon on other days.', fact: 'In hot, dry weather trees close their stomata to save water. They also grow more slowly then.' },
      'breath-10': { name: 'Long breath', how: 'Catch 10 molecules in one breath.', fact: 'A birch leaf has hundreds of thousands of tiny stomata on its underside.' },
      'no-wilt': { name: 'No wilting', how: 'Finish a season without wilting and catch at least 1,500 g.', fact: 'A tree takes up water with its roots and lets it evaporate from its leaves. A big birch can lose tens of litres of water on a summer day.' },
      'week-streak': { name: 'Week streak', how: 'Play seven days in a row.', fact: 'On a good site a young birch can grow up to a metre a year.' },
      'root-care': { name: 'Root care', how: 'Choose Roots three times in a row.', fact: 'Root tips have hair-like root hairs, and fungal threads (mycorrhiza) bring the roots water and nutrients.' },
      'ten-rings': { name: 'Ten rings', how: 'Play ten seasons.', fact: "About half of a tree's dry mass is carbon, and nearly all of it came from the air as carbon dioxide." },
      challenger: { name: 'Challenger', how: 'Send a friend a challenge (coming soon).', fact: "Forest covers about three quarters of Finland's land area." },
      overtake: { name: 'Overtake', how: "Beat a friend's challenge (coming soon).", fact: 'Old black woodpecker holes later become homes for flying squirrels, owls and goldeneye ducks.' },
    },
    log: 'Test log',
    logEmpty: 'No seasons played yet.',
    logClear: 'Clear',
    runs: (n: number) => `${n} seasons played on this device`,
  },
} as const;

/** Emoji only for the copied share text, where chat apps render them well. */
export const WEATHER_EMOJI = { sun: '☀️', cloudy: '⛅', rain: '🌧️', heat: '🌡️' } as const;
